services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Puerto para tu backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: nestdb
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
